<?php

namespace LearningBundle\Repository;

use Doctrine\ORM\EntityManagerInterface;
use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Mapping;
use Doctrine\ORM\ORMException;
use LearningBundle\Entity\Lector;

/**
 * LectorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LectorRepository extends EntityRepository
{
    public function __construct(EntityManagerInterface $em, Mapping\ClassMetadata $metaData = null)
    {
        parent::__construct($em,
            $metaData == null ?
                new Mapping\ClassMetadata(Lector::class) :
                $metaData
        );
    }

    public function insert(Lector $lector)
    {
        try {
            $this->_em->persist($lector);
            $this->_em->flush();
            return true;
        } catch (ORMException $e) {
            return false;
        }

    }

    public function update(Lector $lector)
    {
        try {
            $this->_em->merge($lector);
            $this->_em->flush();
            return true;
        } catch (ORMException $e) {
            return false;
        }
    }
}
