<?php

namespace LearningBundle\Repository;

/**
 * LectorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LectorRepository extends \Doctrine\ORM\EntityRepository
{
}
