<?php

namespace LearningBundle\Repository;

use Doctrine\ORM\EntityManagerInterface;
use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Mapping;
use Doctrine\ORM\ORMException;
use LearningBundle\Entity\User;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{
    public function __construct(EntityManagerInterface $em, Mapping\ClassMetadata $metaData=null)
    {
        parent::__construct($em,
            $metaData == null ?
                new Mapping\ClassMetadata(User::class):
                $metaData
            );
    }

    public function insert(User $user)
    {
        try {
            $this->_em->persist($user);
            $this->_em->flush();
            return true;
        } catch (ORMException $e) {
            return false;
        }

    }

    public function update(User $user){
        try {
            $this->_em->merge($user);
            $this->_em->flush();
            return true;
        } catch (ORMException $e) {
            return false;
        }

    }
}
